---
abstract: 'Upload tarball to my own site'
author:
  - 'Mark Gardner <mjgardner@cpan.org>'
build_requires:
  Carp: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-UploadToSFTP
requires:
  Dist::Zilla::Role::Releaser: 0
  English: 0
  Moose: 0
  MooseX::Has::Sugar: 0
  MooseX::Types::Moose: 0
  Net::Netrc: 0
  Net::SFTP::Foreign::Exceptional: 0
  Try::Tiny: 0
  namespace::autoclean: 0
  perl: 5.008
  utf8: 0
resources:
  bugtracker: https://github.com/mjgardner/Dist-Zilla-Plugin-UploadToSFTP/issues
  repository: git://github.com/mjgardner/Dist-Zilla-Plugin-UploadToSFTP.git
version: 0.001
